export const MODEL_WALLETS = 'wallets'
export const MODEL_SURVEY = 'survey'
export const MODEL_PROPERTIES = 'properties'
export const MODEL_ABOUT_TRANSACTION = 'about-transaction'
export const MODEL_ABOUT_CLAIM_TRANSACTION = 'about-claim-transactions'
